#!/bin/bash
exec {lock_fd}< "$0"
flock --nonblock ${lock_fd} || exit 0

use_sstm=true
ssh_key="/root/.ssh/id_ecdsa"

backup_from="/boot"
target_dir="/volume2/alice_backup/boot"
target_server="backup@192.168.10.4"
sstm_conf="/volume2/alice_backup/sstm.yaml"

target_subdir="current"
target_sstm="/usr/local/sbin/sstm"
backup_to=${target_server}:${target_dir}

nas_backup -e "ssh -i $ssh_key" ${backup_from}/ ${backup_to}/${target_subdir}/

if "${use_sstm}"; then
    ssh ${target_server} sudo ${target_sstm} -c ${sstm_conf} ${target_dir}/${target_subdir} ${target_dir}
fi
